# Generated by Django 3.1.2 on 2020-10-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201025_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlephotos',
            old_name='article',
            new_name='file',
        ),
    ]
