# Generated by Django 3.1.2 on 2020-11-07 09:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, upload_to='articles', verbose_name='Превью'),
        ),
    ]
