# Generated by Django 3.1.2 on 2020-11-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201107_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testclass',
            options={'verbose_name': 'test', 'verbose_name_plural': 'test'},
        ),
    ]
