# Generated by Django 3.1.2 on 2020-11-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201107_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestArticle',
        ),
    ]
