# Generated by Django 3.1.2 on 2020-11-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_testarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestArticle',
        ),
    ]
