# Generated by Django 3.1.1 on 2020-10-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200909_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},
        ),
    ]
