# Generated by Django 3.1.1 on 2020-09-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
