# Generated by Django 3.1.2 on 2020-10-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_item'),
        ('articles', '0003_auto_20201003_0037'),
    ]

    operations = [
    ]
