# Generated by Django 3.1.2 on 2020-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botinfo_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botinfo',
            name='confirmation_token',
            field=models.CharField(max_length=20, verbose_name='Код подтверждения'),
        ),
    ]
